pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
    curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
    apt-get update
    apt-get install -y powershell
    pwsh -c '.\build.ps1'
  displayName: 'Install PowerShell Core and Execute Build'
